######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 4 13:10:05 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS +=  GameBoard.h MainWindow.h
SOURCES +=  GameBoard.cpp main.cpp MainWindow.cpp
